//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCadstar_MAN_DOCs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class mjResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal mjResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eCadstar_MAN_DOCs.mjResources", typeof(mjResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (plot prmfile:&quot;C:\\Users\\mike.jones\\Documents\\eCadstar\\SETTINGS_local\\Manufacture\\ADR\\ADRtb.plot&quot;).
        /// </summary>
        internal static string ADR_Plot_settings {
            get {
                return ResourceManager.GetString("ADR_Plot_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ( print plottername:&quot;PDF&quot; outputfile:&quot;C:/Users/mike.jones/Documents/eCadstar/.mfr/A000xxx-y-CDR.pdf&quot; papersize:4 papersize.x:210 papersize.y:297 direction:&quot;LANDSCAPE&quot; margin.top:0 margin.bottom:0 margin.left:0 margin.right:0 color:&quot;AUTO&quot; coloremphasis:&quot;OFF&quot; clip:&quot;OFF&quot; mirror:&quot;OFF&quot; rotate:0 autoscale:&quot;ON&quot; scale.value:1 autooffset:&quot;ON&quot; offset.x:0 offset.y:0 outputnotfitteditems:&quot;ON&quot; outputunconnectedmark:&quot;OFF&quot; usemoveannotation:&quot;OFF&quot; createbookmark:&quot;OFF&quot; componentbookmark:&quot;OFF&quot; componentpinbookmark:&quot;OFF&quot; netb [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CDR_Print_settings {
            get {
                return ResourceManager.GetString("CDR_Print_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot; ?&gt;
        ///&lt;drill version=&quot;2.0&quot;&gt;
        ///
        ///  &lt;unit type=&quot;mm&quot;/&gt;
        ///
        ///  &lt;basicSettings&gt;
        ///    &lt;targetFile path=&quot;C:/Users/mike.jones/Documents/eCadstar/DESIGNS_local/A000268-5-PCB.pdes&quot;/&gt;
        ///    &lt;outputSettings&gt;
        ///      &lt;outputFolder path=&quot;C:\Users\mike.jones\AppData\Local\Temp\eCad\Gerbils&quot;/&gt;
        ///      &lt;dataFile&gt;
        ///        &lt;suffix enable=&quot;on&quot; string=&quot;fdr&quot;/&gt;
        ///        &lt;noOutputEmptyData mode=&quot;off&quot;/&gt;
        ///      &lt;/dataFile&gt;
        ///      &lt;listFile language=&quot;eng&quot;/&gt;
        ///    &lt;/outputSettings&gt;
        ///    &lt;m [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DrillSettings {
            get {
                return ResourceManager.GetString("DrillSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot; ?&gt;
        ///&lt;photo version=&quot;2.0&quot;&gt;
        ///
        ///  &lt;unit type=&quot;mm&quot;/&gt;
        ///
        ///  &lt;basicSettings&gt;
        ///    &lt;targetFile path=&quot;C:\Users\mike.jones\Documents\eCadstar\DESIGNS_local\A000268-5-PCB.pdes&quot;/&gt;
        ///    &lt;outputSettings&gt;
        ///      &lt;outputFolder path=&quot;C:\Users\mike.jones\AppData\Local\Temp\eCad\Gerbils&quot;/&gt;
        ///      &lt;dataFile&gt;
        ///        &lt;suffix enable=&quot;on&quot; string=&quot;fph&quot;/&gt;
        ///        &lt;noOutputEmptyData mode=&quot;off&quot;/&gt;
        ///      &lt;/dataFile&gt;
        ///      &lt;listFile language=&quot;eng&quot;/&gt;
        ///    &lt;/outputSettings&gt;
        ///    &lt;m [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GbrSettings {
            get {
                return ResourceManager.GetString("GbrSettings", resourceCulture);
            }
        }
    }
}
